### ISSUE TITLE
Localization in lwc open-source 

### ISSUE THREAD

**Issue by ajay312** [salesforce/lwc#2248] opened 2021-02-16 20:18 UTC
Can we use localization like @salesforce/i18n outside Salesforce ?
My url : localhost:3001/?locale=de
From url can I implement localization in lwc which is open-source 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by diervo** [comment] 2021-02-16 20:45
@gonzalocordero can give you some examples.
Moreover we are working on a runtime that will make i18n transparent for you.

**Comment by ajay312** [comment] 2021-02-17 04:54
We are using lwc open-source where we unable to import scoped module '@salesforce/i18n'.. localization for lwc :
We used lang attribute in template but unable to translate template to dynamic language

**Comment by pmdartus** [comment] 2021-02-17 09:17
None of the `@salesforce/*` imports comes out of the box with LWC open source. Those imports are resolved by the Salesforce platform when you publish your code. 

In order to resolve `@salesforce/i18n` (and any other `@salesforce/*` imports), you need to instruct that `@salesforce/i18n` maps to a file on your file system. This is highly dependent on how your project is setup. [Rollup](https://rollupjs.org/) and [Webpack](https://webpack.js.org/) documentations do provide extensive documentation on how to resolve custom imports.

I will close this issue since `i18n` is not part of the core LWC framework. @ajay312 If you are facing issues with custom module resolution feel to share a sample repository so we can help set this up.

**Closed by pmdartus** 2021-02-17 09:17 UTC

**Comment by ajay312** [comment] 2021-02-17 10:21
Thank you @pmdartus But we are trying localization in lwc open source  for translation of page( language,date,number) based on dynamic  locale passed in url..

**Comment by pmdartus** [comment] 2021-02-17 11:43
For date and numbers, I would recommend looking into the built-in [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) object. Those utility methods can be parameterized with the local that you can retrieve from the location query string.

For labels, you will need to load the appropriate labels file dynamically at runtime based on the query string. There is nothing specific about LWC here. You can find interesting articles on this topic online that are applicable to your LWC application.

**Comment by ajay312** [comment] 2021-02-17 11:47
We used Intl functions for date localization using( new Intl.DateTimeFormat(
                    paramValue
                ).format(date);)
How could translate template in Lwc open source with language support?

**Comment by ajay312** [comment] 2021-02-17 11:52
<template>
    <p lang={lang} dir={dir}>Your Current Orders</p>
</template>

Which is not working in lwc open source .
Could you suggest or any inputs for language support ?
Thank you @pmdartus

**Comment by pmdartus** [comment] 2021-02-17 12:08
> How could translate template in Lwc open source with language support?

I am not sure to understand what you are asking for. Could you give a concrete example?

> Which is not working in lwc open source .

The template looks correct. The compiler does produce the same output in open source and on the platform. Could you give a complete example with both JavaScript and HTML files? Could you also explain the expected behavior and the actual behavior?

I would recommend you using webcomponent.dev to share sample code: https://webcomponents.dev/create/lwc

**Comment by ajay312** [comment] 2021-02-17 12:18
Javascript file

export default class App extends LightningElement {
    @track contacts = [];
    @track spinner = false;
    @track jsonresponce;
    lang = "ES";
}

HTML 

    <div   lang="lang">Your Current Orders</div>

Expected behavior

Based on  given language page must translated to that language  from above example your current orders must be display in spanish language 
@pmdartus

**Comment by pmdartus** [comment] 2021-02-17 13:45
The [lang](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang) attribute is just an indication for the browser to indicate the language a specific element. This attribute is treated like any other attribute by LWC. 

For components to render different content depending on the language, you will need to externalize the template content into labels. Those labels are usually stored in JSON files outside your component code. Depending on the user and the query string the appropriate label should then be loaded by the application and injected into the component. There is plenty of resource covering this subject online that is not specific to LWC applications.

**Comment by RupertBarrow** [comment] 2022-02-11 11:17
I would like to add another even more simple use-case to this request : In a component form for entering a <lightning-input-address>, I would like standard data-validation error messages (eg "Complete this field" when a required field is left empty) to display in the language of the user/browser/page.

cc @pmdartus

**Comment by pmdartus** [comment] 2022-02-11 11:50
> In a component form for entering a [... missing ...],

@RupertBarrow I think your last comment is missing a word.
