### ISSUE TITLE
Error thrown when using customElements registry on recursive component structures

### ISSUE THREAD

**Issue by seckardt** [salesforce/lwc#2042] opened 2020-09-23 13:08 UTC
### Description

Given that an LWC component gets registered in the `customElements` registry via its `CustomElementConstructor`, and given that this component internally provides a recursion pattern, the `CustomElementHook.insert` throws an error `Assert Violation: [object:vm Child$1 (11)] cannot be recycled`.

This pattern occurs for instance in a link list component with the pseudo structure like:

```html
<my-link-list>
  <ul>
    <li>Parent
      <my-link-list>
        <ul>
          <li>Child</li>
        </ul>
      </my-link-list>
    </li>
  </ul>
</my-link-list>
```

#### Steps to Reproduce

See here: https://github.com/seckardt/lwc/tree/feature/bug-custom-element-nesting

```js
// x/nested.js
import { api, LightningElement } from 'lwc';
export default class Child extends LightningElement {
    @api hasChild = false;
}
```

```html
// x/nested.html
<template>
    <x-nested if:true={hasChild}></x-nested>
</template>
```

```js
// test case in `integration-karma`
it('should render a nest component structure', () =>{
    const NestedCustomElement = Nested.CustomElementConstructor;
    customElements.define('x-nested', NestedCustomElement);
    const elm = document.createElement('x-nested');
    elm.hasChild = true;
    document.body.appendChild(elm);
});
```

#### Expected Results

No error is thrown

#### Actual Results

`Assert Violation: [object:vm Child$1 (11)] cannot be recycled`

### Browsers Affected

all

### Version

- LWC: 1.8.3

**Possible Solution**

none

**Additional context/Screenshots**

We're facing this issue for instance in Storybook showcases where the `<my-link-list>` component gets registered as a custom element utilizing Storybook's Web Components framework.

**Comment by caridy** [comment] 2020-09-25 02:53
@seckardt thanks for the detailed report. We debugged this issue, and identified the cause. We will be fixing this soon.

**Comment by ravijayaramappa** [comment] 2020-10-07 17:25
Appears to be a duplicate of https://github.com/salesforce/lwc/issues/1975

**Comment by caridy** [comment] 2020-11-13 04:21
might be fixed by https://github.com/salesforce/lwc/pull/2083

**Comment by nolanlawson** [comment] 2022-08-08 23:49
As far as I can tell, this has been fixed. At least, [I can't reproduce](https://stackblitz.com/edit/salesforce-lwc-hsgqqb?file=src/modules/x/nested/nested.html).

![Screen Shot 2022-08-08 at 4 49 40 PM](https://user-images.githubusercontent.com/283842/183533533-19bbe4c6-e220-42cd-8f20-40c6b18aa5bd.png)

Please reopen if I'm mistaken.

**Closed by nolanlawson** 2022-08-08 23:49 UTC
Labels: BUG P2
