### ISSUE TITLE
[engine] non-composed custom events are able to escape shadow root

### ISSUE THREAD

**Issue by apapko** [salesforce/lwc#960] opened 2019-01-14 22:59 UTC
### Description
Steps to reproduce:
- Assign a global event listener ex:
```js
    <script>
        document.addEventListener('enqueue', function(e) {            
            console.log('should not be getting this');
        });
    </script>
```
- From lwc component dispatch a custom event with 'bubbles': true and no 'composed'
```js
        const event = new CustomEvent('enqueue', {
            bubbles: true,
        });
        this.dispatchEvent(event);
```

Actual Result: Event is received by the document
Expected Result: Global event must not be able to escape its shadow root if 'composed': true is not set

**Comment by ravijayaramappa** [comment] 2020-02-13 01:00
Probably duplicate of https://github.com/salesforce/lwc/issues/1700

**Comment by ekashida** [comment] 2020-12-05 06:23
https://github.com/salesforce/lwc/issues/2121

**Closed by ekashida** 2020-12-05 06:23 UTC
