### ISSUE TITLE
Assert violation when using a custom element

### ISSUE THREAD

**Issue by priandsf** [salesforce/lwc#1975] opened 2020-07-10 17:50 UTC
### Description
LWC fails to render a component that is also a custom element.

#### Steps to Reproduce
Clone this project: https://github.com/priandsf/lwc-storybook
```
yarn
yarn build
yarn start
```
It should work.
Now open packages/lwc-library/src/hello/world/world.js
Change hello-world2 to hello-world, save and refresh the browser. It fails with:
lwc-components.js:4602 Uncaught Error: Assert Violation: [object:vm undefined (1)] cannot be recycled.
    at Object.isTrue$1$1 [as isTrue] (lwc-components.js:4602)
    at Object.insert (lwc-components.js:8738)
    at createChildrenHook (lwc-components.js:8579)
    at Object.insert (lwc-components.js:8697)

It seems to appear when the custom element name is the LWC component name. On the other hand, the issue does not appear with its peer component hello/greetings.

### Browsers Affected
Chrome

### Version

- LWC: 1.7.2 (note that it also happened with 1.6.0)

**Comment by diervo** [comment] 2020-07-10 18:02
I remember both @reiniergs and @aputinski had an implementation of LWC working with storybooks, maybe they can share their repos, otherwise @caridy I can take a look next week once we have some time.

**Comment by priandsf** [comment] 2020-07-10 18:26
@diervo yep and we are already talking. This repo is to make it public, but the issue is unrelated.

**Comment by caridy** [comment] 2020-07-12 18:42
probably also related to node reactions PR: https://github.com/salesforce/lwc/pull/1747, which will facilitate this greatly.

**Comment by aputinski** [comment] 2020-07-13 13:57
For what it's worth, here's the long comment I have in our codebase:

```javascript
/*
 This is VERY HACKY

 When the LWC engine adds child components, it calls document.createElement()
 with a tag name that matches the namespace/name of the component,
 even though it's not actually a custom element.

 https://github.com/salesforce/lwc/blob/master/packages/%40lwc/engine-dom/src/apis/create-element.ts#L108

 This causes problems when the engine tries to mount a component
 that is also a registed custom element.

 This hack goes through the source code and adds a prefix to the lwc
 elements so they don't collide with registed custom elements.

 Compiled templates look like this when creating a custom component:
 api_custom_element("th-header-desktop", _thHeaderDesktop, {})
*/
 ```

**Comment by priandsf** [comment] 2020-10-07 01:37
@aputinski @caridy Any news on this one? It is now a blocker for us, and I suspect that there is something wrong in the runtime.

**Comment by nolanlawson** [comment] 2021-06-25 18:29
Is this the same issue as #2191 ?

**Comment by caridy** [comment] 2021-06-29 03:14
Yes, sounds like the same @nolanlawson

**Comment by jodarove** [comment] 2021-06-30 15:58
Duplicate of https://github.com/salesforce/lwc/issues/2191

**Closed by jodarove** 2021-06-30 15:58 UTC
Labels: BUG P3
