### ISSUE TITLE
Issue with the typescript when > Yarn build

### ISSUE THREAD

**Issue by miteshmsharma** [salesforce/lwc#1475] opened 2019-08-26 11:09 UTC
### Description
I am not able to get the LWC project build.
#### Steps to Reproduce
Following along the Contribution document - https://github.com/salesforce/lwc/blob/master/CONTRIBUTING.md
Got stuck with following error - 
$ yarn build
yarn run v1.17.3
$ lerna run build --ignore perf-benchmarks --ignore integration-tests
lerna notice cli v3.16.4
lerna info filter [ '!perf-benchmarks', '!integration-tests' ]
lerna info Executing command in 10 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@lwc/module-resolver' in 12.1s:
$ tsc
lerna ERR! yarn run build exited 2 in '@lwc/style-compiler'
lerna ERR! yarn run build stdout:
$ tsc
src/utils/message.ts(23,5): error TS2741: Property 'plugin' is missing in type '
{ type: "import"; id: string; }' but required in type 'ImportMessage'.
src/utils/message.ts(34,5): error TS2741: Property 'plugin' is missing in type '
{ type: "var-function"; original: string; }' but required in type 'VarFunctionMe
ssage'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

I was also not able to get the project to checkout as the names were long when executing "git clone git@github.com:salesforce/lwc.git". 

How do I fix these issues please?

https://developer.salesforce.com/docs/component-library/tools/playground

```js
const your => (code) => here;
```

### Version

- LWC: x.x.x

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by pmdartus** [comment] 2019-08-26 11:30
What is your version of node?

**Comment by miteshmsharma** [comment] 2019-08-26 12:42
Versions
NPM -  10.14.2 
Yarn - 1.17.3

**Comment by pmdartus** [comment] 2019-08-26 13:07
I wasn't able to reproduce the issues when cloning a fresh new repo. Here are the commands I am using locally:

```sh
git clone git@github.com:salesforce/lwc.git
cd lwc
yarn
```

Maybe I am not able to reproduce it because of the OS. What is your OS, and the OS version?

**Comment by miteshmsharma** [comment] 2019-08-26 13:10
I am on windows 7 home.

**Comment by pmdartus** [comment] 2019-08-26 13:41
I was able to file name length issue on windows 7, this is because until Window 10 the filename length was restricted to 256 characters. Have you tried on a recent version of Windows?

**Comment by miteshmsharma** [comment] 2019-08-26 13:53
The file length issue I have not tried on other window version but if you are aware of this issue and the suggested work around is to use win 10 I will definitely give it a try. Please let me know if the issue with message.ts and error code ts2741 is also related to os?

**Comment by pmdartus** [comment] 2019-08-27 09:55
I tried to reproduce the typescript issue again today without any success. Let me know if you face the same issue on Windows 10.

**Comment by pmdartus** [comment] 2019-12-09 08:56
I will close this issue for now. @miteshmsharma feel free to reopen it if you are still facing this issue.

**Closed by pmdartus** 2019-12-09 08:56 UTC
