### ISSUE TITLE
ebikes lwc sample app failing to install on Summer20 preview

### ISSUE THREAD

**Issue by enthuk** [salesforce/lwc#1912] opened 2020-06-03 10:39 UTC
### Description
When installing the ebikes LWC sample app into a scratch org built with the Summer 20 preview getting errors such as:

Error  force-app/main/default/experiences/E_Bikes1.site-meta.xml  An unexpected error occurred. Please include this ErrorId if you contact support: 123725729-61000 (1302355068)
ERROR running force:source:push:  Push failed.

#### Steps to Reproduce
1. Follow the ebikes install instructions (https://github.com/trailheadapps/ebikes-lwc) using a scratch org
2. After cloning the git repo edit the scratch org config to add    "release": "Preview",
3. Create the scratch org 
4. sfdx force:source:push

Works correctly without the Preview release change.

https://developer.salesforce.com/docs/component-library/tools/playground

```js
const your => (code) => here;
```

### Version

- LWC: x.x.x

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by pmdartus** [comment] 2020-06-03 13:14
This issue is not related to the LWC engine itself. I will close this issue because it's a dupe of https://github.com/trailheadapps/ebikes-lwc/issues/195.

**Closed by pmdartus** 2020-06-03 13:14 UTC
