### ISSUE TITLE
[tests] Ignore compilation of a npm packages not LWC related

### ISSUE THREAD

**Issue by jarrodek** [salesforce/lwc#1816] opened 2020-04-08 20:22 UTC
### Description
In tests I am trying to import the `sinon` library. It results with process crash.

#### Steps to Reproduce
1. Install sinon: `npm i -D sinon`
2. Import the library into your test file: `import sinon from 'sinon/pkg/sinon-esm.js';`
3. Run tests: `npm test`

#### Actual Results
Process crashes.

```
🌟  Using custom configuration from jest.config.js.
🌠  Starting Jest
[BABEL] Note: The code generator has deoptimised the styling of /home/pawel/workspace/anypoint-web-components/awc-mixins/node_modules/sinon/pkg/sinon-esm.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /home/pawel/workspace/anypoint-web-components/awc-mixins/node_modules/sinon/pkg/sinon-esm.js as it exceeds the max of 500KB.

 RUNS  src/modules/awc/mixins/__tests__/HoverableMixin.test.js

<--- Last few GCs --->

[428:0x45b91e0]    46974 ms: Mark-sweep 2034.4 (2063.2) -> 2024.5 (2039.1) MB, 248.5 / 0.0 ms  (+ 836.3 ms in 193 steps since start of marking, biggest step 7.5 ms, walltime since start of marking 1100 ms) (average mu = 0.083, current mu = 0.026) finalize[428:0x45b91e0]    46988 ms: Scavenge 2029.6 (2039.5) -> 2024.3 (2064.8) MB, 10.7 / 0.0 ms  (average mu = 0.083, current mu = 0.026) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x13a71b9]
Security context: 0x0efd198408d1 <JSObject>
    1: allGeneratedPositionsFor(aka SourceMapConsumer_allGeneratedPositionsFor) [0xa21aa0ba159] [/home/pawel/workspace/anypoint-web-components/awc-mixins/node_modules/source-map/lib/source-map-consumer.js:~178] [pc=0x14e0a4396f85](this=0x2cc639c401a9 <BasicSourceMapConsumer map = 0x33d53193f959>,0x252d3a1c9031 <Object map = 0x30aa2edc8ef9>)
    2: /* anonymous */...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x9ef190 node::Abort() [node]
 2: 0x9f13b2 node::OnFatalError(char const*, char const*) [node]
 3: 0xb5da9e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb5de19 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd0a765  [node]
 6: 0xd0adf6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xd1760a v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xd18515 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xd19bbf v8::internal::Heap::HandleGCRequest() [node]
10: 0xcc8715 v8::internal::StackGuard::HandleInterrupts() [node]
11: 0x1024376 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x13a71b9  [node]
Aborted (core dumped)
```

**Comment by pmdartus** [comment] 2020-04-09 09:03
In order to debug and correct the issue, we also need the repository when you run the above commands.

I will close this issue for now. Feel free to re-open the issue when updated with proper reproduction steps.

**Comment by jarrodek** [comment] 2020-04-09 16:44
Why do you need a repo when you have steps to reproduce?

**Comment by jarrodek** [comment] 2020-04-09 16:45
Updated steps to reproduce:
1. Clone the repo: https://github.com/anypoint-web-components/awc-mixin
2 Install dependecies
3. Run test

**Comment by nolanlawson** [comment] 2022-08-08 23:59
In general, OOM errors in Node can be solved by using [`--max-old-space-size`](https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-megabytes).

Based on my reading of this issue, this is probably due to a non-LWC-related package or test using a lot of memory. Please reopen if I'm mistaken.

**Closed by nolanlawson** 2022-08-08 23:59 UTC

**Comment by nolanlawson** [comment] 2022-08-09 00:04
For the record, I could not reproduce (on macOS, Node v16.14.2, npm 8.5.0, using the repro steps of `npm i && npm run test:unit` in the given repo).

Instead, I get a different test failure rather than an OOM. Perhaps this is because Node's memory limit changed in recent versions of Node.

```
⚡⚡⚡⚡⚡  Lightning Web Components ⚡⚡⚡⚡⚡


🌟  Using custom configuration from jest.config.js.
🌠  Starting Jest
 FAIL  src/modules/awc/mixins/__tests__/HoverableMixin.test.js
  HoverableMixin
    LWC element
      Setters and getters
        ✓ Hovered if false by default (10ms)
        ✓ hovered if false by default (5ms)
        ✓ Dispatches hoveredchange event (7ms)
      Entering hover state
        ✓ adds hover state when mouseover event detected (4ms)
        ✓ adds hovered attribute (4ms)
      Leaving hover state
        ✓ removes hover state when mouseleave event detected - LitElement (7ms)
        ✓ adds hovered attribute (7ms)
        ✕ handles light DOM mouseleave (14ms)

  ● HoverableMixin › LWC element › Leaving hover state › handles light DOM mouseleave

    TypeError: Cannot read properties of null (reading 'dispatchEvent')

      91 |           element.hovered = true;
      92 |           const input = element.querySelector('input');
    > 93 |           input.dispatchEvent(new CustomEvent('mouseleave', {
         |           ^
      94 |             // mouseover event bubbles per spec
      95 |             bubbles: true,
      96 |           }));

      at Object.<anonymous> (src/modules/awc/mixins/__tests__/HoverableMixin.test.js:93:11)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 7 passed, 8 total
Snapshots:   0 total
Time:        4.914s
```
