### ISSUE TITLE
Concurrent modification in wire adapters

### ISSUE THREAD

**Issue by priandsf** [salesforce/lwc#1613] opened 2019-11-12 13:44 UTC
### Description
A runtime error is thrown when a component has multiple wire adapters that unregister themselves on disconnect. This is due to a concurrent modification in the collection of listeners (the array is being mutated while iterated).

```js
function invokeListener(listeners: NoArgumentListener[]) {
    for (let i = 0, len = listeners.length; i < len; ++i) {
        listeners[i].call(undefined);
    }
}
```
```js
function handleDisconnect() {
    ...
    eventTarget.removeEventListener('disconnect', handleDisconnect);
}
// Connect the wire adapter
eventTarget.addEventListener('disconnect', handleDisconnect);
```

### Version
- LWC: 1.1.1

**Possible Solution**
Make a copy of the array before iterating and iterate through the copy. The code bellow hasn't been tested but shows the idea:
```js
function invokeListener(listeners: NoArgumentListener[]) {
    const copy = listeners.slice();
    for (let i = 0, len = copy.length; i < len; ++i) {
        copy[i].call(undefined);
    }
}
```

**Comment by kevinv11n** [comment] 2019-11-12 16:33
Dupe of #1458

**Closed by kevinv11n** 2019-11-12 16:33 UTC
