### ISSUE TITLE
Runtime error on Safari

### ISSUE THREAD

**Issue by priandsf** [salesforce/lwc#2376] opened 2021-06-18 15:54 UTC
### Description

This application works well with Chrome and Firefox, but fails with Safari: https://lwc-shop-lightdom.herokuapp.com/
The components are using the Light DOM capability, which might explain while we see patchShadowRoot in the call stack?

#### Steps to Reproduce

Launch the app above with Safari and display the Console. It shows an error like:
```
TypeError: undefined is not an object (evaluating 'p[0]')
runWithBoundaryProtection — lwc-components.js:6901
patchShadowRoot — lwc-components.js:6542
```

```js
  function runWithBoundaryProtection(vm, owner, pre, job, post) {
    let error;
    pre();

    try {
      job();
    } catch (e) {
      error = Object(e);
    } finally {
      post();

      if (!isUndefined$3(error)) {
        addErrorComponentStack(vm, error);
        const errorBoundaryVm = isNull(owner) ? undefined : getErrorBoundaryVM(owner);

        if (isUndefined$3(errorBoundaryVm)) {
           throw error; <<<<<< ERROR HAPPENS HERE <<<<<<
        }
```

App source code is here: https://git.soma.salesforce.com/priand/lwc-shop-lightdom

### Browsers Affected
Safari on OSX (14.1.1) & iOS

### Version
- LWC: 2.2.2

**Comment by pmdartus** [comment] 2021-06-21 10:36
After investigation, the error originates from the `category/category` component [subscription](https://git.soma.salesforce.com/priand/lwc-shop-lightdom/blob/master/src/categories/category/category.js#L62) and not from the LWC engine. A similar error is thrown in Chrome, Firefox, and Safari but with different timings.

In the case of Safari, an incorrect value is emitted sync. The error is first handled by the LWC framework to check if the component can recover from it. As the category component doesn't implement `errorCallback` the error is directly rethrown by the LWC engine.

In the case of Chrome and Firefox, the same incorrect value is emitted async. However, the error is swallowed because the Store nor the Observable doesn't handle uncaught exceptions. You can pause JavaScript execution on uncaught exceptions to verify.

I spent some time investigating why the subscription invocation timing differs between Safari and Chrome/Firefox without success. I will close this issue for now. Feel free to share a minimal reproduction code if the timing issue originates from LWC.

**Closed by pmdartus** 2021-06-21 10:36 UTC
