### ISSUE TITLE
Add new properties for template iterators

### ISSUE THREAD

**Issue by p15i** [salesforce/lwc#2038] opened 2020-09-21 00:19 UTC
**Is your feature request related to a problem? Please describe.**
When building tables of records I've needed to display numberings for each row, and render images in odd and even rows differently.
The default iterator object (https://lwc.dev/guide/html_templates#iterator) at the moment does not contain properties to do this without writing extra code.
The index property doesn't work for numbering which makes sense to end users since it starts at 0, and LWC doesn't allow for JS expressions in HTML attribute values.

**Describe the solution you'd like**
I would like to add the following properties to iterators:
- counter: a 1-indexed number for each iterator item
- odd: boolean value to test if the current value is an odd item in the array
- even: boolean value to test if the current value is an even item in the array

**Describe alternatives you've considered**
At the moment I transform an array to add the above properties after querying from the DB:

```js
let records = /* get records from db */

records.forEach((record, index) => {
  record['counter'] = index + 1;
  record['odd']     = ((index & 1) === 0);
  record['even']    = ((index & 1) !== 0);
});
```

By adding the extra properties, developers would not need to write this extra code.

**Additional context**
I've already implemented the logic to add the new properties (including tests).
It's a fairly simple change (~5 lines of code across 2 files, and 4 updates to unit tests) and doesn't introduce any breaking changes.
I can submit a pull request if there's interest in adding it to the framework.

**Comment by pmdartus** [comment] 2020-09-21 09:12
Thanks for raising this issue @p15i.

I am personally not supportive of adding new capabilities to the `iterator:*` directive. All the capabilities offered by the `iterator:*` directive can be expressed with `for:each` directive with a minimal amount of code, which greatly diminishes the need to keep 2 different directive iterate in LWC.

Instead of updating the record retrieved from the database, I would rather recommend creating a getter to turn your array into something that that can be consumed in the template. This would avoid having to change to original array items for templating only purposes.

```js
import { LightningElement } from 'lwc';

export default class extends LightningElement {
  records = [] // some record from the database
  
  get tableRecords() {
    return this.records.map((record, index) => {
      return {
        ...record,
        row: index + 1,
        odd: index % 2 === 0,
        even: index % 2 === 1
      };
    });
  }
}
```

**Comment by p15i** [comment] 2020-09-23 01:14
I understand, but whether you're mutating an array or implementing a getter you'd have to write out that chunk of code each time you need that feature (kind of what I was hoping to avoid).

There are definitely other developers out there who are running into the same issues, e.g: https://salesforce.stackexchange.com/questions/272487/issue-with-foreach-index-in-lwc

It would be great from an ergonomics viewpoint to have common cases built into the framework (e.g having the first & last properties built-in have definitely been useful).

**Comment by nolanlawson** [comment] 2022-08-08 23:44
Closing as a duplicate of #2521 . I believe with full expression support, this should be possible:

```html
<template iterator:it={items}>
  <li key={it.value}>
    {it.index % 2}
  </li>
</template>
```

Please reopen if I made a mistake.

**Closed by nolanlawson** 2022-08-08 23:44 UTC
