### ISSUE TITLE
Released?  SVG Issue This is issue its been close because the fix has been implemented.

### ISSUE THREAD

**Issue by Lee-Xiao-Long** [salesforce/lwc#1987] opened 2020-07-22 03:36 UTC
This issue was marked as closed, but has it been released?  The last message in the now closed thread from 
@diervo doesn't produce an output - and other tests with elements such as the OPs linearGradient do not appear to work (in the LWC playground).

Here's an example that works in other tools, but not in the LWC playground:

```html
<template>
    <svg
        version="1.1"
        baseProfile="full"
        width={width}
        height={height}
        viewBox="0 0 80 60"
        xmlns="http://www.w3.org/2000/svg"
    >
        <defs>
            <linearGradient id="myGradient" gradientTransform="rotate(90)">
                <stop offset="5%"  stop-color="gold"></stop>
                <stop offset="95%" stop-color="red"></stop>
            </linearGradient>
        </defs>
        <filter id="blurMe">
            <feGaussianBlur stdDeviation="5"/>
        </filter>
        <rect fill="url(#myGradient)" width="80" height="60" rx="8"></rect>
        <rect filter="url(#blurMe)" style="fill: #fff;" x="43" y="18" width="27" height="7" rx="2.95"></rect>
        <rect style="fill: #fff;" x="48" y="32" width="22" height="7" rx="2.95"></rect>
        <path
            style="fill: #fff;"
            d="M17.09,42.12a9.27,9.27,0,0,0-6,3.47c-.83,1-2.6,3.17-1.85,5.31a4.23,4.23,0,0,0,2,2.2H35.75a4.15,4.15,0,0,0,2-2.2c.69-2-.86-4-1.77-5.15-.58-.74-2.61-3.34-5.82-3.71-2.8-.32-3.26,1.42-6.59,1.43S19.94,41.85,17.09,42.12Z"
            transform="translate(0 -10)"
        ></path>
        <ellipse style="fill: #fff;" cx="23.5" cy="22.63" rx="6.8" ry="7.73"></ellipse>
    </svg>
</template>
```

------------------------------------------------------------------
**Original Message from Issue 1367**
https://github.com/salesforce/lwc/issues/1367
------------------------------------------------------------------
This is issue its been close because the fix has been implemented.

While you can't use unary tags since we have to change the html parser which is tricky and time consuming, you can use any filter tag as long as you close the tag like you would do for any non-unary element.

Here is a contrived example that compiles an works:

```html
<svg viewBox="0 0 10 10" xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink">

    <filter id="MyFilter" filterUnits="userSpaceOnUse" x="0" y="0" width="200" height="120">
        <desc>Produces a 3D lighting effect.</desc>
        <feGaussianBlur in="SourceAlpha" stdDeviation="4" result="blur"></feGaussianBlur>
        <feOffset in="blur" dx="4" dy="4" result="offsetBlur"></feOffset>
        <feSpecularLighting in="blur" surfaceScale="5" specularConstant=".75"
                            specularExponent="20" lighting-color="#bbbbbb"
                            result="specOut">
          <fePointLight x="-5000" y="-10000" z="20000"></fePointLight>
        </feSpecularLighting>
        <feComposite in="specOut" in2="SourceAlpha" operator="in" result="specOut"></feComposite>
        <feComposite in="SourceGraphic" in2="specOut" operator="arithmetic"
                     k1="0" k2="1" k3="1" k4="0" result="litPaint"></feComposite>
        <feMerge>
          <feMergeNode in="offsetBlur"></feMergeNode>
          <feMergeNode in="litPaint"></feMergeNode>
        </feMerge>
      </filter>
      </svg>

```

If a particular filter or element within an svg does not work feel free to file a seprate issue with a repro and details.

_Originally posted by @diervo in https://github.com/salesforce/lwc/issues/1367#issuecomment-621663744_

**Comment by ekashida** [comment] 2020-07-26 01:12
The original issue was resolved some time ago. Looks like this is happening due to id-mangling applied to the `linearGradiant` id:
```
<linearGradient id="myGradient-1" gradientTransform="rotate(90)">
  <stop offset="5%" stop-color="gold"></stop>
  <stop offset="95%" stop-color="red"></stop>
</linearGradient>
```

**Comment by nolanlawson** [comment] 2022-08-08 23:52
Closing as apparently the issue is fixed. Please reopen if I'm mistaken.

**Closed** 2022-08-08 23:52 UTC
