### ISSUE TITLE
[engine] remove or improve @api mutation message 

### ISSUE THREAD

**Issue by apapko** [salesforce/lwc#1089] opened 2019-03-05 00:08 UTC
### Description
Users are reporting an excess amount of warning from the engine related to @api mutation:

> [LWC warning]: If property value decorated with @api in [object:vm undefined (33)] is used in the template, the value 001xx000003GaAVAA0 set manually may be overridden by the template, consider binding the property only in the template.

Expected:
1. We either remove this warning all together
2. Or improve the message to include mutation origin, such as the field being mutated, its class and the parent that is passing the value? Something like: "x-child shouldn't attempt to override the value of @api 'foo' received from the x-parent.

**Comment by caridy** [comment] 2019-08-12 14:14
@ekashida can you close this?

**Comment by ekashida** [comment] 2019-08-14 05:16
Confirmed that this error log was removed.

**Closed by ekashida** 2019-08-14 05:16 UTC
Labels: BUG P3

**Comment by BatemanVO** [comment] 2020-01-23 19:12
I recently performed an `npm i @salesforce/lwc-jest` to update my lwc-jest and am now on version 0.5.5. I am still seeing the warning `If property x decorated with @api in [object:vm undefined (y)] is used in the template, the value z set manually may be overriden by the template, consider binding the property only in the template.`.

It looks like #1193 should've removed that error from the warnings and was merged last May and this issue was closed in August.

Was it added back in in a future PR, or is there something I'm missing about updating my version to pick up the change from that PR?

**Comment by pmdartus** [comment] 2020-01-24 09:34
@BatemanVO What version of LWC are you running? If you don't know could you share your npm or yarn lock file?

**Comment by BatemanVO** [comment] 2020-01-24 17:53
@pmdartus 0.5.5. That's the version I have when I run `npm i @salesforce/lwc-jest`.

**Comment by ravijayaramappa** [comment] 2020-01-24 18:48
@BatemanVO @salesforce/lwc-jest@0.5.5 was released prior to fix #1193. Please [install](https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.unit_testing_using_jest_installation) the latest version(0.6.2) of @salesforce/sfdx-lwc-jest(previously named @salesforce/lwc-jest) and the errors should go away.

**Comment by BatemanVO** [comment] 2020-01-24 19:34
@ravijayaramappa Thank you - I did not know the package had been renamed, that was the key to fixing the problem.
