### ISSUE TITLE
Allow access to Slot elements from the component

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/lwc#2092] opened 2020-11-13 10:21 UTC
**Is your feature request related to a problem? Please describe.**
No. It is a feature request.

I want to access the list of `slots` from within the parent

````html
<template>
    <div>
        <slot></slot>
    </div>
</template>
````

````js
import { api, LightningElement } from 'lwc';

export default class Parent extends LightningElement {

    connectedCallback(){
         //parent has access to slots
         this.slots.forEach((slot) => {
            console.log(slot);
        }

    }

}
````

**Describe the solution you'd like**
`this.slots` must be accessible from parent

**Describe alternatives you've considered**
use `lwc:dom`

**Comment by Bartheleway** [comment] 2021-02-03 13:29
Hi @AllanOricil, I believe your issue is somehow similar to mine #2218 in a more complex example. It doesn't seems possible currently to have slot in loop.

**Comment by AllanOricil** [comment] 2021-02-03 15:36
@Bartheleway yes, it would be necessary to implement scoped slots as Vue js does.

**Comment by nolanlawson** [comment] 2022-08-08 23:25
This sounds like a request for what we're calling "scoped slots": https://github.com/salesforce/lwc-rfcs/pull/63 . The reason I think so is because you're wanting to have slots inside of a for-loop and to pass for-loop-specific information into those slots (e.g. the current iteration index).

Closing as a duplicate of https://github.com/salesforce/lwc/issues/210, please reopen if I'm mistaken.

**Comment by AllanOricil** [comment] 2022-08-09 10:14
@nolanlawson it is related, but I'm not sure if #210 would also expose `this.slots` in the parent js class. If it does, then you can keep this closed

**Comment by nolanlawson** [comment] 2022-08-09 18:15
Hm, you're right, the proposal doesn't seem to allow programmatic access to the `<slot>` elements; in fact I believe they are not true `<slot>`s because native shadow DOM does not support scoped slots. Template refs (#2690) would also not address this since they are not true `<slot>`s.

**Comment by AllanOricil** [comment] 2023-05-14 16:34
Delivered 23
Thank you @nolanlawson

**Closed** 2023-05-15 17:02 UTC
Labels: enhancement
