### ISSUE TITLE
Node.isConnected return false on Nodes in shadow tree on IE11

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#987] opened 2019-01-21 09:17 UTC
### Description

`Node.isConnected` returns `false` instead of `true` on IE11 for Nodes part of the shadow tree.

```js
const elm = createElement('x-test', { is: Test });
document.body.appendChild(elm);

expect(elm.shadowRoot.querySelector('div').isConnected).toBe(true);
// Actual: false (IE11)
// Expected: true
```

### Browsers Affected
- IE11

### Version
- LWC: 0.35.4

**Comment by caridy** [comment] 2019-08-12 13:52
@ravijayaramappa I think you were working on the polyfill for `isConnected` as part of the node-reactions. Can you confirm, and get this one fixed?

**Comment by caridy** [comment] 2019-08-12 13:59
this is in fact a duplicate of https://github.com/salesforce/lwc/issues/1029, which shows the polyfill code as well.

**Closed by caridy** 2019-08-12 13:59 UTC
Labels: UA/Polyfills, bug
