### ISSUE TITLE
Named export with a default export LightningElement makes template querySelector only return SecureObject

### ISSUE THREAD

**Issue by Vacster** [salesforce/lwc#2194] opened 2021-01-18 20:37 UTC
### Description
Having a named export in the same file as a (default exported) class that extends LightningElement makes all querySelectors on the template return SecureObjects that can't be modified.

#### Steps to Reproduce
1. Create a basic LWC with a single lightning-input
2. On renderedCallback have a query selector modify the value of the lightning-input
     2A. Verify the value in the lightning-input is changed
3.  Add a simple export of a const string
    3A. Try to run and see error saying `Cannot add property value, object is not extensible`

```js
import { LightningElement } from 'lwc'

export const BREAKING_EXPORT = 'sample'
export default class Break extends LightningElement {
    renderedCallback() {
        this.template.querySelector('lightning-input').value = 'It works'
    }
}
```
```html
<template>
    <lightning-input label="Test Input" value="It did not work"></lightning-input>
</template>
```

#### Expected Results
The lightning-input's value is updated

#### Actual Results
Error is thrown saying: `Cannot add property value, object is not extensible`.
Trying to log what is being returned by the `this.template.querySelector` call shows it's a SecureObject.

### Browsers Affected
Google Chrome Version 87.0.4280.141 (Official Build) (x86_64)

### Version
- LWC: v1.10.0
- Salesforce api: 50.0

**Additional context/Screenshots**
Example error in Salesforce:
![image](https://user-images.githubusercontent.com/10774499/104960516-a7516400-59d4-11eb-809d-b272cb4665b3.png)

Stack trace from error:
```
TypeError: Cannot add property value, object is not extensible
    at Breaks.renderedCallback (https://new10--dev.lightning.force.com/lightning/r/Case/5001l000006KtDbAAK/modules/c/breaks.js:34:62)
    at callHook (https://new10--dev.lightning.force.com/auraFW/javascript/brGGs47DxbvfWhvsxC5ggQ/aura_proddebug.js:19150:37)
    at https://new10--dev.lightning.force.com/auraFW/javascript/brGGs47DxbvfWhvsxC5ggQ/aura_proddebug.js:10383:9
    at runWithBoundaryProtection (https://new10--dev.lightning.force.com/auraFW/javascript/brGGs47DxbvfWhvsxC5ggQ/aura_proddebug.js:11096:7)
    at invokeComponentRenderedCallback (https://new10--dev.lightning.force.com/auraFW/javascript/brGGs47DxbvfWhvsxC5ggQ/aura_proddebug.js:10376:7)
    at runRenderedCallback (https://new10--dev.lightning.force.com/auraFW/javascript/brGGs47DxbvfWhvsxC5ggQ/aura_proddebug.js:10787:5)
    at patchShadowRoot (https://new10--dev.lightning.force.com/auraFW/javascript/brGGs47DxbvfWhvsxC5ggQ/aura_proddebug.js:10770:7)
    at rehydrate (https://new10--dev.lightning.force.com/auraFW/javascript/brGGs47DxbvfWhvsxC5ggQ/aura_proddebug.js:10731:7)
    at appendVM (https://new10--dev.lightning.force.com/auraFW/javascript/brGGs47DxbvfWhvsxC5ggQ/aura_proddebug.js:10598:5)
    at Object.insert (https://new10--dev.lightning.force.com/auraFW/javascript/brGGs47DxbvfWhvsxC5ggQ/aura_proddebug.js:9368:9)
```

The named export can be imported normally into other components and works perfectly fine. Methods decorated with @api can still be accessed by a parent component.

**Comment by pmdartus** [comment] 2021-01-19 08:08
Thanks for opening this issue @Vacster. 
This is a duplicate of #1891.

**Closed by pmdartus** 2021-01-19 08:08 UTC

**Comment by Vacster** [comment] 2021-01-19 08:13
You're right @pmdartus , it's the same issue. My bad, guess I didn't search enough before opening a new one.
