### ISSUE TITLE
Error when rendering the same stylesheet to two different documents (iframes, templates)

### ISSUE THREAD

**Issue by jmrog** [salesforce/lwc#2609] opened 2021-12-16 17:19 UTC
### Description

This issue appears to affect Chrome only, and happens if (1) your `lwc` version is >= 2.3.7, (2) you render an LWC component using `lwc:dom="manual"`, (3) your manually-constructed DOM also includes an LWC component, and (4) the LWC component in the manually-constructed DOM has its own CSS stylesheet. If any of those conditions are not satisfied (e.g., you use `lwc` version <= 2.3.4, or the LWC component in the manually-constructed DOM does not have its own stylesheet), the issue does not occur.

**The issue:** under the aforementioned conditions, in Chrome, the `lwc` library throws an uncaught DOMException, and the app fails to render (crashes). The DOMException is as follows:

```
Uncaught DOMException: Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot': Sharing constructed stylesheets in multiple documents is not allowed
    at insertConstructableStyleSheet (http://localhost:3001/app-d1335320964653800ef9.js:7691:35)
    at Object.insertStylesheet (http://localhost:3001/app-d1335320964653800ef9.js:7887:13)
    at createStylesheet (http://localhost:3001/app-d1335320964653800ef9.js:5973:18)
    at http://localhost:3001/app-d1335320964653800ef9.js:6209:71
    at ReactiveObserver.observe (http://localhost:3001/app-d1335320964653800ef9.js:597:7)
    at isUpdatingTemplate (http://localhost:3001/app-d1335320964653800ef9.js:6178:9)
    at runWithBoundaryProtection (http://localhost:3001/app-d1335320964653800ef9.js:7201:5)
    at evaluateTemplate (http://localhost:3001/app-d1335320964653800ef9.js:6163:3)
    at invokeComponentRenderMethod (http://localhost:3001/app-d1335320964653800ef9.js:6370:39)
    at renderComponent (http://localhost:3001/app-d1335320964653800ef9.js:6428:18)
    at rehydrate (http://localhost:3001/app-d1335320964653800ef9.js:6795:22)
    at connectRootElement (http://localhost:3001/app-d1335320964653800ef9.js:6551:3)
    at callNodeSlot (http://localhost:3001/app-d1335320964653800ef9.js:7919:9)
    at HTMLDivElement.appendChild (http://localhost:3001/app-d1335320964653800ef9.js:7929:16)
    at http://localhost:3001/app-d1335320964653800ef9.js:8437:15
    at NodeList.forEach (<anonymous>)
    at App.insertDocHtml (http://localhost:3001/app-d1335320964653800ef9.js:8428:14)
    at App.renderedCallback (http://localhost:3001/app-d1335320964653800ef9.js:8448:12)
    at callHook (http://localhost:3001/app-d1335320964653800ef9.js:6523:13)
    at http://localhost:3001/app-d1335320964653800ef9.js:6300:5
    at runWithBoundaryProtection (http://localhost:3001/app-d1335320964653800ef9.js:7201:5)
    at invokeComponentCallback (http://localhost:3001/app-d1335320964653800ef9.js:6299:3)
    at runRenderedCallback (http://localhost:3001/app-d1335320964653800ef9.js:6881:5)
    at patchShadowRoot (http://localhost:3001/app-d1335320964653800ef9.js:6853:5)
    at rehydrate (http://localhost:3001/app-d1335320964653800ef9.js:6796:5)
    at connectRootElement (http://localhost:3001/app-d1335320964653800ef9.js:6551:3)
    at callNodeSlot (http://localhost:3001/app-d1335320964653800ef9.js:7919:9)
    at HTMLDivElement.appendChild (http://localhost:3001/app-d1335320964653800ef9.js:7929:16)
    at http://localhost:3001/app-d1335320964653800ef9.js:25006:33
    at http://localhost:3001/app-d1335320964653800ef9.js:25007:3
    at http://localhost:3001/app-d1335320964653800ef9.js:25194:12
```

The error is thrown at the moment that the `adoptedStylesheets` property of the `target` is assigned in `insertConstructableStyleSheet`.

#### Steps to Reproduce

I created a very small GitHub repo that reproduces the issue: [https://github.com/jmrog/lwc-stylesheets-bug](https://github.com/jmrog/lwc-stylesheets-bug). I was unable to reproduce the issue in the webcomponents.dev environment, but am unsure what version of `lwc` is being used there anyway. The steps to reproduce the issue are available on the just-mentioned repo, but here they are again:

0. Clone the repo and run `yarn install` or `npm install`.
1. Start the application using `yarn watch` or `npm run watch`.
2. Direct Chrome to http://localhost:3001 to open the app.
3. Observe that nothing renders.
4. Open the browser's developer tools and observe the error mentioned above.

Again, the issue does not appear if you remove the child component's CSS file, or if you do not construct the DOM manually (e.g., change `this.isManual = true;` to `this.isManual = false;` in the constructor in `app.js`), or if you downgrade `lwc` enough (e.g., downgrading `lwc-services` to `3.1.0` in the aforementioned repo works), etc. It also does not appear in Firefox or Safari (only Chrome, as far as I know).

#### Expected Results

The app renders as expected, and no error is thrown. Visual from the above repo:

![image](https://user-images.githubusercontent.com/8409748/146417444-9c54df86-886f-49bc-9d3e-5a156d3b00f4.png)

#### Actual Results

The app fails to render (crashes) and shows an uncaught DOMException in the browser console, in Chrome only. Visual from the above repo:

![image](https://user-images.githubusercontent.com/8409748/146418564-14a142e0-6b86-44ee-b2c1-478d5cd7289f.png)

### Browsers Affected

Chrome, latest version (96.0.4664.110 as of this writing).

### Version

- LWC: 2.3.7+

### Possible Solutions

Not really a solution, but just want to note that the changes introduced in #2460 seem to have triggered this issue.

**Comment by nolanlawson** [comment] 2021-12-16 19:54
Thanks for the very thorough bug report! I wrote a minimal repro (https://github.com/nolanlawson/lwc-barebone/commit/431bec0c1e96197cf5847b8a3ccbb46ebd219515) based on yours:

```js
document.body.appendChild(createElement("x-app", { is: App }));

const template = document.createElement('template');
template.content.appendChild(createElement("x-app", { is: App })); // throws
```

The issue is that (apparently) adopted stylesheets cannot be reused across two documents – in this case, the main document and a `<template>`. Iframes have the same issue:

```js
document.body.appendChild(createElement("x-app", { is: App }));

const iframe = document.createElement('iframe');
iframe.contentDocument.appendChild(createElement("x-app", { is: App }));  // throws
```

One workaround you can use is to avoid `<template>`s. For instance, here is a modified version of your repro (https://github.com/nolanlawson/lwc-stylesheets-bug/commit/014de8599871f6f802b542b1d4911a2372d277a5) that doesn't throw an error.

We could try to track constructable stylesheets on a per-document basis, but I'm not sure if that's feasible. This is a tricky bug, and there's some more discussion of it here: https://github.com/WICG/construct-stylesheets/issues/23

**Comment by jmrog** [comment] 2021-12-16 22:01
@nolanlawson Nice minimal repro, and thanks for the workaround. As far as my team is concerned, that workaround is sufficient -- and _extremely_ minimal in cost -- for us to move to the latest version of `lwc`.

Thanks for the link to that discussion, too. Lots to think about there!

**Comment by nolanlawson** [comment] 2022-03-01 20:23
So this is actually a really subtle issue. I have a [minimal repro](https://bl.ocks.org/nolanlawson/raw/3417c1534640355b382e2ab0cf6b6ee7/):

```js
  const template = document.createElement('template')
  const div = document.createElement('div')
  div.attachShadow({ mode: 'open' })
  template.content.appendChild(div)

  const sheet = new CSSStyleSheet()
  div.shadowRoot.adoptedStyleSheets = [sheet]
```

In Chrome this throws:

> DOMException: Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot': Sharing constructed stylesheets in multiple documents is not allowed

In Firefox with the flag `layout.css.constructable-stylesheets.enabled` enabled, it throws:

> DOMException: ShadowRoot.adoptedStyleSheets setter: Each adopted style sheet's constructor document must match the document or shadow root's node document

Looking through various discussions on this (e.g. https://github.com/WICG/construct-stylesheets/issues/133 and [this Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1111864)), I'm not sure if there's a solution. There is no way AFAICT to associate the CSSStyleSheet's [constructor document](https://drafts.csswg.org/cssom/#concept-css-style-sheet-constructor-document) with the template's owner document. Apparently there are elaborate solutions involving [adoptNode](https://developer.mozilla.org/en-US/docs/Web/API/Document/adoptNode), but I haven't yet gotten them to work.

In iframes, I assume this would not be a problem, because assuming the LWC engine is running inside the iframe, it would be getting `CSSStyleSheet` from the `window` of the iframe, not the containing page. So maybe this just affects templates.

**Comment by nolanlawson** [comment] 2022-03-01 21:57
Interestingly [the same pattern works fine with Lit](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudH0gZnJvbSAnbGl0L2RlY29yYXRvcnMuanMnO1xuXG5AY3VzdG9tRWxlbWVudCgnc2ltcGxlLWdyZWV0aW5nJylcbmV4cG9ydCBjbGFzcyBTaW1wbGVHcmVldGluZyBleHRlbmRzIExpdEVsZW1lbnQge1xuICBzdGF0aWMgc3R5bGVzID0gY3NzYHAgeyBjb2xvcjogcmVkIH1gO1xuXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGA8cD5IZWxsbyE8L3A-YDtcbiAgfVxufVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiPlxuICBjb25zdCB0ZW1wbGF0ZSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ3RlbXBsYXRlJyk7XG4gIGNvbnN0IGRpdiA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ3NpbXBsZS1ncmVldGluZycpO1xuICBkaXYuYXR0YWNoU2hhZG93KHsgbW9kZTogJ29wZW4nIH0pO1xuICB0ZW1wbGF0ZS5jb250ZW50LmFwcGVuZENoaWxkKGRpdik7XG4gIFxuICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKHRlbXBsYXRlLmNvbnRlbnQuY2xvbmVOb2RlKHRydWUpKVxuICA8L3NjcmlwdD5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjEuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl4zLjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0). The difference is this:

```js
  const template = document.createElement('template');
  const div = document.createElement('x-foo');
  div.attachShadow({ mode: 'open' });
  template.content.appendChild(div); // LWC assigns adoptedStyleSheets here
  
  document.body.appendChild(template.content.cloneNode(true)) // Lit assigns adoptedStyleSheets here
```

The reason for the difference is that LWC doesn't use the "real" `connectedCallback`, and we fire it at the incorrect time. [Minimal repro](https://github.com/nolanlawson/lwc-barebone/commit/c365e18e69b0120943a7bea4701a99cd9e7e2fcb):

![Screen Shot 2022-03-01 at 1 54 27 PM](https://user-images.githubusercontent.com/283842/156255551-7b430498-438f-4f01-857e-33e98b7d7ec4.png)

If we fix that bug, then assigning `adoptedStyleSheets` should "just work."

**Comment by nolanlawson** [comment] 2022-03-01 22:50
Turns out you don't even need a `<template>`; you can [repro](https://github.com/nolanlawson/lwc-barebone/commit/a25bd06002efe1ace69d077e2351d06e410f5f85) with a `<div>`:

```js
  const div = document.createElement('div');
  console.log('appending to div')
  div.appendChild(elm);
  console.log('appending div to document.body')
  document.body.appendChild(div);
```

![Screen Shot 2022-03-01 at 1 54 27 PM](https://user-images.githubusercontent.com/283842/156262134-8bf556f7-2c25-454a-bf08-6094a1afec19.png)

**Comment by nolanlawson** [comment] 2022-05-26 17:01
Related to https://github.com/salesforce/lwc/issues/1102

**Comment by pmdartus** [comment] 2023-01-20 08:23
Duplicate of #3198

**Closed by pmdartus** 2023-01-20 08:23 UTC
Labels: BUG P2
