### ISSUE TITLE
`innerHTML` on a Light DOM component that contains a Shadow DOM element with slots, returns a string with `<slot>`.

### ISSUE THREAD

**Issue by abdulsattar** [salesforce/lwc#2352] opened 2021-06-02 10:13 UTC
### Description
`innerHTML` on a Light DOM component that contains a Shadow DOM element with slots, returns a string with `<slot>`.
#### Steps to Reproduce
1. Create a Light DOM component
2. Embed a Shadow DOM component that has slots in it
3. Get `innerHTML` of the Light DOM component element.

#### Expected Results
`innerHTML` does not contain `<slot>` tag.

#### Actual Results
`innerHTML` does contains `<slot>` tag. It doesn't strip them off.

**Comment by nolanlawson** [comment] 2021-06-02 16:57
As discussed today, this is also reproducible without light DOM components, by appending the shadow DOM component to a regular `div` and then calling `innerHTML` on the `div`.

[Repro](https://github.com/pmdartus/lwc-barebone/commit/2f2dc2f3483ed661e06321ff6de247cbcd6b6b8f):

![Screen Shot 2021-06-02 at 9 54 50 AM](https://user-images.githubusercontent.com/283842/120520613-da473380-c388-11eb-90a7-eb76f60f02ab.png)

(In native shadow, the inner HTML would be `<x-app></x-app>`.)

**Comment by gregwhitworth** [comment] 2022-01-10 16:56
@abdulsattar @nolanlawson Should this be closed out then?

**Comment by nolanlawson** [comment] 2022-01-10 18:38
I think this should be fixed by #2549. It looks like a dup of #2425.

**Comment by nolanlawson** [comment] 2022-01-10 18:41
Yep I just confirmed using the repro; this is fixed by #2549. Before and after:

![Screen Shot 2022-01-10 at 10 41 05 AM](https://user-images.githubusercontent.com/283842/148820945-16953701-42a2-4452-aea0-d7a810914981.png)
![Screen Shot 2022-01-10 at 10 41 09 AM](https://user-images.githubusercontent.com/283842/148820950-7327f7a3-0b4e-491f-b8f2-21f843292dc7.png)

**Comment by nolanlawson** [comment] 2022-01-10 18:41
Duplicate of https://github.com/salesforce/lwc/issues/2425

**Closed by nolanlawson** 2022-01-10 18:41 UTC
