### ISSUE TITLE
Framework exception handling and debugging.

### ISSUE THREAD

**Issue by bk-dev** [salesforce/lwc#2273] opened 2021-03-22 14:56 UTC
### Description
When attempting to debug generic JS bugs, the framework surfaces them in such a way that they are difficult to debug.

#### Steps to Reproduce
```js
connectedCallback() {
    console.log(foo); // foo is not defined
}
```

#### Expected Results
A stack trace which provides a line number and method name along with the JS error.

#### Actual Results
When the framework handles the exception it surfaces the correct error message, but the only clue the stack trace provides is the component where the exception was thrown.

**Comment by nolanlawson** [comment] 2022-08-08 23:20
I'm sorry for the late reply. However, I was not able to reproduce this issue. [Here is my test case](https://stackblitz.com/edit/salesforce-lwc-6vwe9a?file=src/modules/x/app/app.js).

In the logs, I see:

```
Uncaught ReferenceError: foo is not defined
    at App.connectedCallback (main.js:8190:17)
    at callHook (main.js:5774:13)
    at main.js:5556:5
    at runWithBoundaryProtection (main.js:6403:5)
    at invokeComponentCallback (main.js:5555:3)
    at runConnectedCallback (main.js:6214:5)
    at connectRootElement (main.js:5802:3)
    at callNodeSlot (main.js:8044:5)
    at HTMLBodyElement.appendChild (main.js:8061:12)
    at main.js:8204:15
```

This seems to provide adequate information for debugging the problem.

If this is an issue with a specific part of the Salesforce platform, please reopen if you have more details to share. Closing this issue for now, please reopen if I've closed it by mistake.

**Closed by nolanlawson** 2022-08-08 23:20 UTC
