### ISSUE TITLE
Switching between multiple templates leaks css

### ISSUE THREAD

**Issue by joan-sf** [salesforce/lwc#2793] opened 2022-04-13 20:26 UTC
### Description
When having multiple templates with different css and switching between them, the latest one to apply is the one that ends up winning. Switching back to the first template keeps the css of the previous one.

#### Steps to Reproduce
1. Generate a new project with
```
$ npm init lwr
$ npm install
$ npm run start
```
2. Create a component with two templates, as described on the [docs](https://lwc.dev/guide/html_templates#render-multiple-templates)
3. Add the respective route to lwr.config.json
4. Enter the component and switch templates

#### Expected Results

Css is scoped to the respective html template

#### Actual Results

Css from different template is being applied

### Browsers Affected

Chrome 100.0, Safari 15.4, Firefox 98.0.2

### Version

- LWC: 2.5.8
- LWR: 0.6.4

**Additional context/Screenshots**
This happens if you select either Typescript or Javascript project template
It also happens when using the [Recipes App](https://github.com/trailheadapps/lwc-recipes-oss)
The only place where I couldn't reproduce the issue is on [webcomponent.dev](https://webcomponents.dev/edit/eq4kPYgbHF66mkS8Ocf2/src/app.html?p=stories)

**Comment by nolanlawson** [comment] 2022-04-13 21:21
Thanks for reporting. I believe this is a duplicate of #2466.

Currently, replacing template A with template B does not guarantee that template A's styles will be removed from the DOM. For this reason, we recommend developers to use styles that only apply to that particular template, and to not rely on the other template's styles not being present.

We may fix #2466 eventually, but it would be tricky because it could potentially break backwards compatibility, if developers are relying on the styles _not_ being removed.

Please let me know if I've diagnosed the problem correctly, and reopen this issue if I'm wrong. Thanks!

**Closed by nolanlawson** 2022-04-13 21:21 UTC

**Comment by joan-sf** [comment] 2022-04-18 13:40
Thx for the ultra quick response. I totally understand the potential break on backwards compatibility, my suggestion would be to remove the multiple template example from the [docs](https://lwc.dev/guide/html_templates#render-multiple-templates), or at least mention that css is not completely scoped from one template to the other

**Comment by nolanlawson** [comment] 2022-04-18 16:15
Yeah that example in the docs only works in old versions of LWC, or in non-Chrome browers, due to some subtleties in how styles are rendered. (Constructable stylesheets versus style tags.) It should probably be changed.

**Comment by nolanlawson** [comment] 2022-05-03 18:05
@joan-sf FWIW, the CSS does not "leak" between templates in a multi-template component if you use [scoped styles](https://rfcs.lwc.dev/rfcs/lwc/0116-light-dom-scoped-styles). So that is one potential workaround.

**Comment by joan-sf** [comment] 2022-05-03 19:50
Oh nice, gonna do some reading on light dom to understand exactly how scoped styles may solve the issue and check with the team if it's something we should consider using. Either way, thank you so much for the update and suggestion!

**Comment by nolanlawson** [comment] 2022-05-03 21:35
@joan-sf Scoped styles can be used in either light DOM or shadow DOM. 🙂  In either case, they avoid the multi-template CSS leakage problem (https://github.com/salesforce/lwc/pull/2797#issuecomment-1116391759).

**Comment by nolanlawson** [comment] 2022-06-16 18:15
@joan-sf [The documentation](https://lwc.dev/guide/html_templates#render-multiple-templates) has been updated to recommend scoped styles for this use case, and the demo is fixed. Thank you for raising this issue. 🙂

**Comment by joan-sf** [comment] 2022-06-16 19:34
Glad to help!
And thank you for the quick responses and detail suggestion on how to solve the issue
