### ISSUE TITLE
LWC for:each render not optimized 

### ISSUE THREAD

**Issue by tiagoshadow** [salesforce/lwc#2760] opened 2022-03-24 16:58 UTC
When constructing a Component for a Virtual Table, I've noticed a stutter in the performance, I've done the same component in React and it works fine. I've investigated it and saw that while rendering new rows (my code removes x rows from the one end, and add the same number to the other end when scrolling) the engine was replacing every column, even those which did not change, key and content was the same.

Here is a video of the example I've https://streamable.com/qpc8pr
Here is the code, with a workaround implemented, to reproduce the steps, push the promise code outside of the promise
https://webcomponents.dev/edit/zm01qk8oaWr5sMvZfiDU/src/app.js?p=stories

So instead of:
```js
    moveDown() {
        const amount = 2;
        this.start = Math.max(this.start + amount, 0);
        this.end = Math.min(this.end + amount, this.processedRows?.length || 0);
        this.visibleRows.push(...this.processedRows.slice(this.end - amount, this.end));
        Promise.resolve().then(() => this.visibleRows.splice(0, amount));
    }

    moveUp() {
        const amount = 2;
        this.start = Math.max(this.start - amount, 0);
        this.end = Math.min(this.end - amount, this.processedRows?.length || 0);
        this.visibleRows.unshift(...this.processedRows.slice(this.start, this.start + amount));
        Promise.resolve().then(() => this.visibleRows.splice(this.visibleRows.length - amount, amount));
    }
```
It should look like this
```js
    moveDown() {
        const amount = 2;
        this.start = Math.max(this.start + amount, 0);
        this.end = Math.min(this.end + amount, this.processedRows?.length || 0);
        this.visibleRows.push(...this.processedRows.slice(this.end - amount, this.end));
        this.visibleRows.splice(0, amount);
    }

    moveUp() {
        const amount = 2;
        this.start = Math.max(this.start - amount, 0);
        this.end = Math.min(this.end - amount, this.processedRows?.length || 0);
        this.visibleRows.unshift(...this.processedRows.slice(this.start, this.start + amount));
        this.visibleRows.splice(this.visibleRows.length - amount, amount);
    }
```

I had an issue on StackOverflow and was advised to create an issue here, I do not use LWC in node js, I use LWC in Salesforce itself, so not sure if this is the best place to solve both.

**Comment by nolanlawson** [comment] 2022-03-24 20:52
Thanks for reporting. I don't quite understand the issue; the example is a bit complex. Some questions:

1. In your demo app, you're using `setTimeout` rather than `Promise.resolve()`, so I'm not sure how to "push the promise code outside of the promise." Do you have an example that demonstrates the slowness, without any modifications?
2. Does this only occur only when you have a `for:each` inside of another `for:each`, as in your `app.html`?
3. Does this occur if you modify the `this.visibleRows` in one line rather than two, e.g. by creating a new array and setting it once?

I also cannot reproduce the issue you show in your video, where you scroll and the `<p>` elements in the DevTools Elements panel are flashing (indicating they are being updated). When I test (even after removing the `setTimeout()`s), they don't flash.

**Comment by tiagoshadow** [comment] 2022-03-24 21:50
Hi @nolanlawson, yes its a complex scenario
1. Sorry, did not publish the right change, [here](https://webcomponents.dev/edit/rrDbQTmB4d6fNXpU2Mh1) is an example where the problem happens, with only one for:each loop.
2. Yes as shown by the example
3. Yes, using something like slice results in the same problem, it is separated because the workaround that I've found is that if I push x rows first and let it render, and then unshift the same amount the system behaves as it is supposed to

**Comment by nolanlawson** [comment] 2022-03-24 22:04
@tiagoshadow Thank you for the simplified example. Unfortunately I still cannot reproduce. Here is what I do:

1. Click the link to [your demo](https://webcomponents.dev/edit/rrDbQTmB4d6fNXpU2Mh1)
2. Open the Chrome DevTools
3. Scroll the list

In your video, the `<p>` elements are flashing. In my DevTools, they are not.

Can you reproduce in a Guest/Incognito window without any browser extensions? I notice in your video that you have several browser extensions installed.

**Comment by tiagoshadow** [comment] 2022-03-25 00:20
Hi @nolanlawson, yes issue still happens in Incognito with no Extensions active, [I've recorded here](https://streamable.com/lqi09h)

**Comment by nolanlawson** [comment] 2022-03-25 16:13
Hi @tiagoshadow I think you may have sent the wrong video? It shows a recording of this GitHub issue page.

**Comment by tiagoshadow** [comment] 2022-03-25 16:26
@nolanlawson it does not let me record my anonymous screen, I've disabled all the extensions instead and recorded, I also recorded in Firefox, and it seems that it only happens in Chrome. [Recording](https://streamable.com/pdqfyb)

**Comment by nolanlawson** [comment] 2022-03-25 17:10
@tiagoshadow Thanks for the clarification. I've created a reduced version of your repro [here](https://github.com/nolanlawson/lwc-barebone/commit/bd9d7fd92a5228a8dbe18a27cd44439b6e863a80) and I can reproduce in Chrome.

The issue is that Move Down causes all the child `<p>` elements to flash (indicating change) whereas Move Up does not. 

Move Up refers to appending items to the end and removing items from the start:

![Screen Shot 2022-03-25 at 9 58 39 AM](https://user-images.githubusercontent.com/283842/160167145-f09a2a6a-a162-4680-9cf5-5af75af29708.png)

![Screen Shot 2022-03-25 at 9 57 33 AM](https://user-images.githubusercontent.com/283842/160167159-f443ed75-3705-4f79-8423-cb9a8a7c400b.png)

Whereas Move Down refers to prepending items to the start and removing items from the end:

![Screen Shot 2022-03-25 at 9 58 35 AM](https://user-images.githubusercontent.com/283842/160167062-b94ffe08-7ff2-40d2-ba6b-4ba1ccf65854.png)

![Screen Shot 2022-03-25 at 9 57 30 AM](https://user-images.githubusercontent.com/283842/160167074-78813843-22cb-464c-8eed-91ef8d29c6b1.png)

(Note 5 `<p>` flashes for Move Down, and 2 for Move Up.)

I think this is just a quirk of how Chrome DevTools shows element updates. When I check how many times a new element is actually created with `document.createElement`, I see that it is only called twice for both Move Up and Move Down:

![Screen Shot 2022-03-25 at 9 54 25 AM](https://user-images.githubusercontent.com/283842/160167321-ea879935-fb1a-4581-bd73-80395f7c6da4.png)

Furthermore, I wrote [a test](https://github.com/nolanlawson/lwc-1/commit/a5e20e0aacc9bebc3bdfdd77da9f2110facc788b) to check that the 3 unchanged elements are exactly the same when prepending and appending. The tests both pass.

Also, as you mention, Firefox shows different flashing:

![Screen Shot 2022-03-25 at 10 05 46 AM](https://user-images.githubusercontent.com/283842/160168008-8ce6eace-c429-4d6b-8a76-940228947fcc.png)

![Screen Shot 2022-03-25 at 10 05 36 AM](https://user-images.githubusercontent.com/283842/160167997-eff40276-5bc0-4c99-9fb8-7ca015433270.png)

I think we can close this as a Chrome DevTools-specific issue. If you are still seeing stuttering in your app, please provide a Chrome DevTools Performance Timeline trace to see if it is caused by LWC. And if you have a specific recommendation for how we could improve DOM rendering, please let me know. 🙂 

Closing for now, please reopen if my analysis is mistaken.

**Closed by nolanlawson** 2022-03-25 17:10 UTC

**Comment by tiagoshadow** [comment] 2022-03-25 17:50
@nolanlawson, your conclusion is correct, after playing with my code a bit more I saw that there is everything if fine, performance is pretty much the same, the only performance hit is when I click very quickly to shift multiple times, but that I can tweak on my side, maybe a recommendation to improve performance on this case would be to if the Object that causes the rerender is the same to stop the previous iteration and continue with a new one. I tried to build my own react copy framework using standard web elements, so I know that this is not so trivial
