### ISSUE TITLE
Compile error when using <data value="> element within template.

### ISSUE THREAD

**Issue by 32bitkid** [salesforce/lwc#1484] opened 2019-08-30 15:21 UTC
### Description

The `<data>` element does not appear to be properly supported. It appears that the parser is [_aware_](https://github.com/salesforce/lwc/blob/v1.0.3/packages/@lwc/template-compiler/src/parser/utils/html-element-attributes.ts#L133) that the `<data>` element has a `value` attribute, but it throws a compile error every time I try to use it.

#### Steps to Reproduce

https://developer.salesforce.com/docs/component-library/tools/playground/PWT4SwG-D/1/edit

#### Expected Results
No error is throw

#### Actual Results
```
LWC1057: value is not valid attribute for data. For more information refer to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/data
```

**Comment by caridy** [comment] 2019-08-30 15:58
Hmm, this is suspicious! Indeed it is defined well in our code https://github.com/salesforce/lwc/blob/master/packages/@lwc/template-compiler/src/parser/utils/html-element-attributes.ts#L133, but for some reason it is failing.

@apapko @jodarove can you take a look?

**Comment by apapko** [comment] 2019-08-30 16:46
I'm unable to reproduce this issue with the latest lwc version (locally). 
@caridy, the internal playground yields a successful compilation as well, even when with lwc 1.0.0.

**Comment by apapko** [comment] 2019-08-30 16:54
@midzelis, any clues why the public playground would produce a different result?

**Comment by sfdc-jkovitz** [comment] 2020-08-25 22:40
@caridy @apapko @32bitkid 
I've picked this one back up. Like Alex I can't reproduce locally, or in the new version of the playground, or here:
https://lwc-playground.dev/projects/R8hOtSMny/3/edit

Can we assume this bug no longer applies, or any suggestions for next steps? Thanks

**Comment by nolanlawson** [comment] 2023-08-11 18:13
[I am not able to repro either](https://stackblitz.com/edit/salesforce-lwc-2txxdj?file=src%2Fmodules%2Fx%2Fapp%2Fapp.html). Closing for now, please reopen as necessary.

**Closed by nolanlawson** 2023-08-11 18:13 UTC
Labels: bug

**Comment by vaugood** [comment] 2025-03-24 06:01
I was getting this error. I replace the double-quotes with single-quotes. That fixed it.
