### ISSUE TITLE
Unable to validate activeElement of lwc in Jest

### ISSUE THREAD

**Issue by mitchwoloschek** [salesforce/lwc#2299] opened 2021-04-20 20:48 UTC
### Description
I am unable to validate which input on a form is focused on using `this.template.activeElement` while in the context of a jest test. In the `onchange` handler I include a check to verify if event's target is the same as the activeElement and if so focus on the next input in the form. `this.template.activeElement` is always null so the conditional never gets executed to focus on the next input.

#### Steps to Reproduce
Here's a base code example

form
```
<lightning-input
    data-id="accountName"
    name="accountName"
    label="Account"
    variant="label-hidden"
    value={accountName}
    onchange={handleLookupChange}
></lightning-input>

<lightning-input
    data-id="contactName"
    name="contactName"
    label="Contact"
    variant="label-hidden"
    value={contactName}
    onchange={handleLookupChange}
></lightning-input>
```

input change handler
```
handleLookupChange(event) {
        event.stopPropagation();

        **some logic here.

        // if this input still has focus, move it to the next input
        if (event.target === this.template.activeElement) {
            **navigate to next input
        }

        this.dispatchChangeEvent();
    }
```

jest test
```
it('focuses on the contact input after account is selected', async () => {
    // Given
    const element = createElement('c-form', { is: form });
    document.body.appendChild(element);

    const changeHandler = jest.fn();
    element.addEventListener('change', changeHandler);
    const contactLookup = element.shadowRoot.querySelector('[data-id="contactName"]');
    contactLookup.focus = jest.fn(); // mock the focus method so we can check if it was called

    // When
    await flushPromises();

    const accountInput = element.shadowRoot.querySelector('[data-id="accountName"]');
    accountLookup.value = mockAccount.Name;
    accountInput.dispatchEvent(new CustomEvent('focus'));
    accountLookup.dispatchEvent(new CustomEvent('change'));

    // Then
    await flushPromises();
    expect(contactLookup.focus.mock.calls.length).toBe(1);
});
```

#### Expected Results
Expect jest test to pass. Contact input's focus method called once.

#### Actual Results
Contact input's focus method has not been called.

### Version

**Possible Solution**
There were some suggestions to use `this.template.host.getRootNode().activeElement` as a workaround but that did not fix issue.

**Comment by nolanlawson** [comment] 2022-08-08 23:17
Sorry for the late reply. I could not reproduce in a browser environment (either with or without synthetic shadow), so this does indeed seem to be a Jest-specific issue.

I found this JSDOM issue, which has been closed: https://github.com/jsdom/jsdom/issues/2602

Hopefully the issue has been resolved. Please reopen if I closed this bug by mistake.

**Closed by nolanlawson** 2022-08-08 23:17 UTC
