### ISSUE TITLE
Synthetic shadow rendering slots incorrectly

### ISSUE THREAD

**Issue by mrigdon** [salesforce/lwc#2029] opened 2020-09-15 17:17 UTC
### Description

When rendering an LWC component that has slots _outside of LWC_ (i.e. defining it in `customElements` and adding it to an index.html) _with synthetic shadow enabled_, the slotted content is not rendered where expected -- instead it is always rendered on top of all the content in the component body.

The issue is only reproducible with synthetic shadow enabled. Here is a full example: https://github.com/mrigdon/lwc-test

#### Steps to Reproduce

1. Create a component that has slot(s)
```html
<!-- widget.html -->
<template>
  <div>header</div>
  <slot></slot>
  <div>footer</div>
</template>
```
2. Import the component in index.js, define in custom element registry, and bundle with rollup
```js
import '@lwc/synthetic-shadow';
import Widget from 'my/widget';
customElements.define('my-widget', Widget.CustomElementConstructor);
```
3. Import the bundle and add component to index.html
```html
...
<body>
  <my-widget>content</my-widget>
  <script src="bundle.js"></script>
</body>
```

#### Expected Results

Browser output should look like this:

```
header
content
footer
```

#### Actual Results

Browser output looks like this (content rendered before header):

```
content
header
footer
```

When commenting out the synthetic shadow import, the output is correct.

### Browsers Affected

- Chrome
- Safari
- Firefox

### Version

- LWC: 1.7.14

**Possible Solution**

n/a

**Additional context/Screenshots**

- full example: https://github.com/mrigdon/lwc-test
- Example DOM output: 
<img width="249" alt="Screen Shot 2020-09-15 at 10 16 27 AM" src="https://user-images.githubusercontent.com/7377110/93243089-8cc46100-f73c-11ea-82fd-9b3bfede553f.png">

**Comment by FabienHuot** [comment] 2021-04-12 17:09
I have the same issue. Is there something new ?

**Comment by FabienTaillon** [comment] 2021-04-29 13:27
I'm having this issue too.

The weird thing is that it doesn't work with an app created with the [`create-lwc-app`]:(https://github.com/muenzpraeger/create-lwc-app) tool
![image](https://user-images.githubusercontent.com/2465122/116557726-02adbf00-a8ff-11eb-97c9-581cbb5a5ffc.png)

However, the exact same OSS code is working on webcomponents.dev:
![image](https://user-images.githubusercontent.com/2465122/116557793-16592580-a8ff-11eb-8a8e-3ccb469a7b0b.png)

Here is the working link:
https://webcomponents.dev/edit/4JD17Tza34ZLLZ8HyCeE

Both seems to use the synthetic shadow, so I don't know why the webcomponents.dev works. 
I don't know where to check which version of the lwc compiler is used for both of them.

**Comment by FabienTaillon** [comment] 2021-05-03 09:08
@Gr8Gatsby any input on a fix for this one ? You flagged it as P1 more than 7 months ago and is quite a pain for OSS projects.

**Comment by caridy** [comment] 2021-05-06 21:17
Ok, sorry for not paying attention to this issue, somehow it escapes my nets.

This is not a bug, but a limitation of synthetic shadow. A root element (from LWC or from a web component of an LWC) does not accept content to be slotted. We are not going to attempt to make this work, instead, the workaround is quite simple, you create another component that does not expect content, and set the content for `my-widget` inside its template, and everything will work just fine.

To give you more details, this is the number one reason why in Aura you can't have a LWC in the markup while passing content into it.

**Closed by caridy** 2021-05-06 21:17 UTC
Labels: BUG P1

**Comment by FabienTaillon** [comment] 2021-05-07 16:16
@caridy thank you for the clarification.
If I understood correctly, this problem should only happen at the root level, but not for child components, am I right ?

We have an internal project where we're having the same issue but not at the root level.
For instance here we have a `texei-app` component (the one created with `createElement`), including a `texei-child` component, including a `lightning-card` where we can see that the slots aren't rendered correctly even though it's not at the root.

![image](https://user-images.githubusercontent.com/2465122/117477652-8d756600-af5e-11eb-82a2-91fb7491c35b.png)

I can see the same result as on this [issue](https://github.com/salesforce/lwc/issues/2146).

I can't reproduce it on webcomponents.dev though.

If you confirm that it's supposed to work, I'll try to clean the project to have a repro on a public repo.

**Comment by FabienTaillon** [comment] 2021-05-07 16:19
Also it doesn't work with a custom component so it's not an issue with base components:
![image](https://user-images.githubusercontent.com/2465122/117479460-a7b04380-af60-11eb-8d7a-17f3a04c8750.png)

**Comment by FabienTaillon** [comment] 2021-06-14 20:28
@caridy I was finally able to find what's the difference that makes slots working or not.

They are working when import are done in this order:
```
import '@lwc/synthetic-shadow';
import { createElement } from 'lwc';
```

However it's not working the other way round:
```
import { createElement } from 'lwc';
import '@lwc/synthetic-shadow';
```

I created 2 repos and heroku apps showing this (they are 100% the same, except this import order):
### OK
**Repo:** https://github.com/FabienTaillon/lwc-oss-slots-ok
**heroku app:** https://lwc-oss-slots-ok.herokuapp.com

### KO
**Repo:** https://github.com/FabienTaillon/lwc-oss-slots-ko
**heroku app:** https://lwc-oss-slots-ko.herokuapp.com

I used [this blog post](https://developer.salesforce.com/blogs/2020/12/build-connected-apps-anywhere-using-lightning-base-components.html) to create these apps.

Beside the issues already link to this one, this may also be the issue with some others like #2147.

**Comment by caridy** [comment] 2021-06-15 03:28
Ah, yes, synthetic shadow MUST be loaded first. Loading it after LWC could have very unpredictable results. cc @nolanlawson @pmdartus
