### ISSUE TITLE
Grammar limitation in templates

### ISSUE THREAD

**Issue by TwoPlusTwoOne** [salesforce/lwc#2060] opened 2020-10-16 18:17 UTC
### Description
When writing LWC directives, it is possible to use property accessors such as:
```
<template for:each={myList} for:item="item">
      <my-component-item item={item} key={item.id}> <--- property accessor
      </my-component>
</template>
```
It is not, however, possible to use the alternative way or writing property accessors, such as:
```
<template for:each={myList} for:item="item">
      <my-component-item item={item} key={item['@id']}> <--- this is not allowed
      </my-component>
</template>
```

#### Steps to Reproduce
Create a component that iterates over a property array, in which the objects have a field called `@id`, and try to use this id as the key for the iteration in the template

```
<template for:each={myList} for:item="item">
      <my-component-item item={item} key={item['@id']}> <--- this is not allowed
      </my-component>
</template>
```

#### Expected Results
No error is thrown, property is accessed correctly

#### Actual Results
Error is thrown, cannot compile

### Browsers Affected
N/A

### Version
- LWC: 1.7.9

**Comment by nolanlawson** [comment] 2022-08-08 23:28
Thanks for reporting. Closing as a duplicate of #2521

**Closed by nolanlawson** 2022-08-08 23:28 UTC
