### ISSUE TITLE
[synthetic-shadow] slotchange event not triggered

### ISSUE THREAD

**Issue by jbverger** [salesforce/lwc#1846] opened 2020-04-22 11:38 UTC
### Description
With synthetic shadow on, onslotchange is not triggered.

#### Steps to Reproduce

```html
<template>
    <slot onslotchange={handleSlotChange}></slot>
</template>
```

```js
import "@lwc/synthetic-shadow";

handleSlotChange (e) {
    console.log("New slotted content");
}
```

#### Expected Results
slotchange event triggered.

#### Actual Results
slotchange event not triggered

### Version
- LWC: 1.3.7

**Comment by pmdartus** [comment] 2020-04-22 12:57
Thanks @jbverger for reporting this issue. I will have close this since it is not respecting the issue template because it lacks either a link to a playground or a minimal reproduction case that exhibits the issue.

Here is an example of the slotchange event on the [playground](https://developer.salesforce.com/docs/component-library/tools/playground/oBNfNTCwZ/1/edit) (note the playground uses `@lwc/synthetic-shadow` by default). Feel free to reopen an issue with a proper repro case if you are still facing the same bug.

**Closed by pmdartus** 2020-04-22 12:57 UTC

**Comment by jbverger** [comment] 2020-04-22 17:40
Thanks @pmdartus, the issue happen when I register my LWC as a Web Component with customElements.define('my-cmp', buildCustomElementConstructor(MyCmp));. Is it related to https://github.com/salesforce/lwc/issues/1351? 
Thanks for your help,

**Comment by caridy** [comment] 2020-04-22 18:14
Yeah, that's pretty much it @jbverger, two solutions at this point:

1. create a new LWC component that wraps the one you're using + the things you're passing into it as slots.
2. use native shadow.

**Comment by jbverger** [comment] 2020-04-22 18:17
Ok perfect. Thanks @caridy
