### ISSUE TITLE
unable to modify inner dom element of shadow element

### ISSUE THREAD

**Issue by surendra-dev** [salesforce/lwc#1587] opened 2019-10-21 11:44 UTC
Hi Folks,

I am writing a component with resize text area based on height, it will be auto resize. I created following code with playground.
https://developer.salesforce.com/docs/component-library/tools/playground/goOTvmp1t/1/edit

But when same code i write in my app then it gives me that shadowRoot is undefined.

Thanks in advance

**Comment by caridy** [comment] 2019-10-22 00:45
@surendra-dev you need to provide more details. I suspect you're running LWC in standalone mode. I also suspect you're using IE or Edge, both of them do not support native shadow, in which case you have to load our synthetic-shadow package. But that's just me guessing! /cc @Gr8Gatsby

**Comment by surendra-dev** [comment] 2019-10-22 07:10
Hi @caridy ,

Thank you so much for quick response.

So very first i am using same code in chrome browser only. Code that i am trying to run is part of org. 
I am attaching few screenshot for your reference.

![image](https://user-images.githubusercontent.com/22252793/67264474-c8bd5a80-f4c8-11e9-962b-525186f84881.png)

![html-code](https://user-images.githubusercontent.com/22252793/67264496-d8d53a00-f4c8-11e9-9d58-21f49fc5b816.PNG)

Also have a query not sure if that make sense for this or not. It could be version issue of LWC of playground and my org ?

Thanks in advance.

**Comment by caridy** [comment] 2019-10-22 15:00
Ok, the issue here is that you're introspecting into the internal details of lighting-textarea with the following line in your code:

```
this.template.querySelectorAll('lightning-textarea')[0].shadowRoot.querySelector('textarea')
```

Basically, you're attempting to get into `lighting-textarea`'s shadowRoot, which is illegal in our platform because you're crossing a namespace boundary between `c` namespace and `lightning` namespace. And locker service is going to enforce that, while the playground does not support locker service just yet. /cc @KrisGraySFDC 

Closing since this is working as intended.

Feel free to open an issue for `lightning-textarea` on the proper channel to provide a way to support this use-case.

**Closed by caridy** 2019-10-22 15:00 UTC
