### ISSUE TITLE
Enable `passive` and `once` options when adding listeners to Components, Custom Elements and Shadow Roots

### ISSUE THREAD

**Issue by caridy** [salesforce/lwc#420] opened 2018-06-15 20:14 UTC
Because of the fallback mechanism in the synthetic shadow, we need to queue the listeners adding to Components, Custom Elements and Shadow Roots, and because of that queue, we can't support `passive` or `once` options.

We should attempt to solve this at some point. The workaround is to add those manually in `renderedCallback()` on a regular element in your template, or on the slot element, and by doing so, you can use the options there. Keep in mind that this also requires some branch check to avoid adding that multiple times since `renderedCallback()` is invoked after every render.

**Comment by pmdartus** [comment] 2021-02-05 11:53
Dupe of https://github.com/salesforce/lwc/issues/1824.

**Closed by pmdartus** 2021-02-05 11:53 UTC
